name: Cypress E2E Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript (if necessary)
        run: npm run build # Ensure TypeScript is compiled, adjust if using another bundler like Vite

      - name: Start the client (port 3000)
        run: npm run dev -- --port 3000 & # Start the Vite client in the background

      - name: Start the server (port 3001)
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: npm run server -- --port 3001 & # Start the server in the background

      - name: Wait for server and client to be ready
        run: |
          # You might want to wait for the server and client to be fully up before running tests
          # For example, use a small delay or a tool like `wait-on`
          npx wait-on http://localhost:3000
          npx wait-on http://localhost:3001

      - name: Run Cypress E2E tests
        run: npx cypress run --headless # Running in headless mode for CI
