name: Cypress E2E Tests

on:
  # Trigger for any pull request activity on the develop branch (create, update)
  pull_request:
    branches:
      - develop

concurrency:
  # Filtering on the current branch ref helps avoid concurrency
  group: ${{ github.ref }}
  # Cancel running lint jobs
  cancel-in-progress: true

jobs:
  test:
    name: Checking E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript (if necessary)
        run: npm run build

      - name: Start the client (port 3000)
        run: npm run client:dev & # Start the Vite client in the background

      - name: Start the server (port 3001)
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: npm run start & # Start the server in the background

      # - name: Wait for server and client to be ready
      #   run: |
      #     # You might want to wait for the server and client to be fully up before running tests
      #     # For example, use a small delay or a tool like `wait-on`
      #     npx wait-on http://localhost:3000
      #     npx wait-on http://localhost:3001

      - name: Run Cypress E2E tests
        run: npx cypress run --e2e --headless  # Run E2E tests in headless mode
